cours/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from cours.views import *

app_name = "cours"
urlpatterns = [
    
    path('', accueil, name='accueil'),
    path('courses/', NiveauListView.as_view(), name='niveau_liste'),
    path('courses/editeur/', sauvegader, name='sauvegader'),
    path('courses/creer/', leconCreateView.as_view(), name='lesson_creer'),
    path('courses/<slug:slug>/', MatiereListView.as_view(), name='matiere_liste'),
    path('courses/<str:niveau>/<slug:slug>/', LeconListView.as_view(), name='lesson'),
    path('courses/<str:niveau>/<slug:matiere>/<slug:slug>', LeconDetailView.as_view(), name='lesson_detail'),
    path('courses/<str:niveau>/<slug:matiere>/<slug:slug>/modifier', LeconUpdateView.as_view(), name='lecon_modifier'),
    path('courses/<str:niveau>/<slug:matiere>/<slug:slug>/supprimer', LeconDeleteView.as_view(), name='lecon_supprimer'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT)

proedututo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include("cours.urls")),
    path('counts', include('utilisateurs.urls')),
    path('quizzes/', include('quizzes.urls')),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path("__reload__/", include("django_browser_reload.urls")),
]

templates/base/home.html
{% extends "main.html" %}
{% load static %}
{% block content_page %}
<div class="mx-auto">
  <div class="p-3 rounded-lg mt-8 mb-3 w-full">
    <h1 class="text-4xl font-semibold text-gray-800 my-3 text-center">Créez le Web de Demain, Apprenez HTML et CSS
      Aujourd'hui !</h1>
    <img src="{% static 'images/accueil.png' %}" alt="Image d'accueil" class="w-full h-96 object-cover rounded-lg mb-4">
    <p class="text-gray-600 text-3xl text-center my-8">Découvrez notre contenu passionnant et engageant.</p>
  </div>
  <div class="grid grid-cols-3 gap-3 pl-44 pr-44">
    {% for matiere in matieres %}
    <div class="w-80 h-72 bg-white shadow-md mx-6 mb-4 rounded-lg overflow-hidden">
      <a href="{% url 'cours:lesson'  slug=matiere.slug  niveau=matiere.niveau.slug  %}">
        <img src="{{ matiere.image.url }}" alt="{{matiere.nom|upper}}" class="w-28 h-24 mx-auto pt-2  object-cover">
        <div class="p-4">
          <h2 class="text-xl font-semibold mb-2 text-center">{{matiere.nom|upper}}</h2>
          <p class="text-gray-600 text-center">{{matiere.description|truncatewords:10}}</p>
          <div class="mt-4 text-center">
            <a href="{% url 'cours:lesson'  slug=matiere.slug  niveau=matiere.niveau.slug %}"
              class="bg-blue-500 hover:bg-blue-600 text-white px-4 py-2 rounded-md inline-block">Apprendre</a>
          </div>
          <div class="mt-1 text-right">
            <span class="text-sm text-gray-400 ">Niveau : {{matiere.niveau}}</span>
          </div>
        </div>
      </a>
    </div>
    {% empty %}

    {% endfor %}
  </div>
</div>
{% endblock content_page %}